Repository Kernel360/FE1_E2E_sumtime, pull requests merged in 2024-08, with the labels that each got.

#34 feat: turso, drizzle 연동 및 api 설계
  .env
  drizzle.config.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app/api/todo/add/route.ts
  src/app/api/user/add/route.ts
  src/app/api/user/emailValidation/route.ts
  src/app/api/user/loginValidation/route.ts
  src/app/apiTest/page.tsx
  src/app/page.tsx
  src/db/index.ts
  src/db/schema.ts
  src/db/schema/todos.ts
  src/db/schema/users.ts
  tests-examples/demo-todo-app.spec.ts
Labels: feat

#33 feat: index 페이지 ui 완성
  src/app/HomePage.styled.ts
  src/app/page.tsx
Labels: feat

#32 [feat] theme 파일 생성
  src/components/common/Card.styled.tsx
  src/components/common/index.tsx
  src/themes/index.ts
Labels: feat

#36 [refactor] 공통 컴포넌트 확장자 .tsx -> .ts로 변경
  src/components/common/Container.styled.ts
  src/components/common/Flex.styled.ts
  src/components/common/Input.styled.ts
  src/components/common/Text.styled.ts
  src/components/common/index.ts
  src/themes/index.ts
Labels: refactor

#40 feat: Slot 컴포넌트 추가 구현
  jest.config.ts
  package-lock.json
  package.json
  src/app/page.tsx
  src/timetable/components/Slot.module.scss
  src/timetable/components/Slot.tsx
  src/timetable/components/TaskSlot.tsx
  src/timetable/components/Timetable.tsx
  src/timetable/constants/index.ts
  src/timetable/mocks/timetableMockData.ts
  src/timetable/utils/index.ts
  src/timetable/utils/timeTable.util.test.ts
Labels: feat

#41 feat: Todo CRUD api 완성
  src/app/api/todo/add/route.ts
  src/app/api/todo/create/route.ts
  src/app/api/todo/delete/route.ts
  src/app/api/todo/getAllByUserId/route.ts
  src/app/api/todo/getOneByTodoId/route.ts
  src/app/api/todo/update/route.ts
  src/app/api/user/add/route.ts
  src/app/api/user/create/route.ts
  src/app/api/user/getIdByEmail/route.ts
  src/app/apiTest/page.tsx
  src/db/schema/users.ts
Labels: feat

#47 feat: Time Table Custom setting & slot random color
  .eslintrc.json
  src/app/timetable/components/Slot.tsx
  src/app/timetable/components/TaskSlot.tsx
  src/app/timetable/components/TimeSlot.tsx
  src/app/timetable/components/Timetable.tsx
  src/app/timetable/components/Timetable.type.ts
  src/app/timetable/constants/index.ts
  src/app/timetable/mocks/timetableMockData.ts
  src/app/timetable/utils/color.ts
  src/app/timetable/utils/height.ts
  src/app/timetable/utils/index.ts
  src/app/timetable/utils/tests/parseHeightString.test.ts
Labels: feat

#51 feat : 투두 컴포넌트 기본 로직 구현 ; api 연동 X
  package-lock.json
  package.json
  src/app/MainTest/page.tsx
  src/components/common/BasicContainer.styled.ts
  src/components/common/Container.styled.ts
  src/components/common/Input.styled.ts
  src/components/common/Text.styled.ts
  src/components/common/index.ts
  src/components/todo/Todo.styled.ts
  src/components/todo/TodoComponent.tsx
  src/components/todo/TodoModal.tsx
  src/components/todo/index.tsx
  src/hooks/index.ts
  src/hooks/utils/useBooleanState.ts
Labels: feat

#49 feat: next auth 프로젝트 연동
  .gitignore
  next.config.mjs
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/todo/page.tsx
  src/components/SignIn/SignInButton.tsx
  src/components/SignIn/SignOutButton.tsx
  src/components/common/AuthProvider.tsx
  src/lib/auth.ts
Labels: feat

#61 feat: tanstack query 적용
  .env
  .gitignore
  package-lock.json
  package.json
  src/app/api/todo/create/route.ts
  src/app/api/todo/delete/route.ts
  src/app/api/todo/getAllByUserId/route.ts
  src/app/api/todo/getOneByTodoId/route.ts
  src/app/api/todo/update/route.ts
  src/app/api/user/create/route.ts
  src/app/apiTest/calls/todoCalls.ts
  src/app/apiTest/calls/userCalls.ts
  src/app/apiTest/page.tsx
  src/app/layout.tsx
  src/db/schema/todos.ts
  src/utils/ReactQueryProviders.tsx
Labels: refactor, feat

#66 refactor: tanstack query 훅 분리 및 타입 정의
  src/app/api/todo/delete/route.ts
  src/app/apiTest/calls/todoCalls.ts
  src/app/apiTest/calls/userCalls.ts
  src/app/apiTest/hooks/todoQueries.ts
  src/app/apiTest/hooks/userQueries.ts
  src/app/apiTest/page.tsx
Labels: refactor

#62 feat : todo api 연결 (tanstack query X)
  src/app/layout.tsx
  src/components/todo/TodoComponent.tsx
  src/components/todo/TodoModal.tsx
  src/components/todo/index.tsx
Labels: fix, feat

#64 refactor: time table 컴포넌트 style 하나로 합치기
  src/app/timetable/components/Slot.module.scss
  src/app/timetable/components/Timetable.module.scss
  src/app/timetable/components/TypeTimeTable/RowTypeTimeTable.module.scss
  src/app/timetable/components/TypeTimeTable/Slot.tsx
  src/app/timetable/components/TypeTimeTable/TaskSlot.tsx
  src/app/timetable/components/TypeTimeTable/TaskSlotItem.tsx
  src/app/timetable/components/TypeTimeTable/TimeSlot.tsx
  src/app/timetable/components/TypeTimeTable/TypeTimeTable.module.scss
  src/app/timetable/components/TypeTimeTable/index.tsx
  src/app/timetable/utils/css.ts
  src/app/timetable/utils/index.ts
Labels: refactor

#72 fix: 실제 시간과 CurrentTimeLine의 차이 좁히기
  src/app/timetable/components/CurrentTimeLine/CurrentTimeLine.module.scss
  src/app/timetable/components/CurrentTimeLine/index.tsx
  src/app/timetable/components/Timetable.tsx
  src/app/timetable/components/TypeTimeTable/index.tsx
  src/app/timetable/utils/index.ts
Labels: fix

#87 docs: README.md 작성
  README.md
  image-1.png
  image-2.png
  image-3.png
  image-4.png
  image-5.png
  image-6.png
  image-7.png
  image.png
Labels: docs, NOW

#83 feat: credential 로그인 기능 구현
  src/app/page.tsx
  src/app/todo/page.tsx
  src/components/SignIn/SignInButton.tsx
  src/components/SignIn/SignOutButton.tsx
  src/components/login/index.tsx
  src/components/signup/index.tsx
  src/lib/auth.ts
  src/types/next-auth.d.ts
Labels: feat, 5PM

#84 feat: currentTimeLineStyle 속성 추가 및 구현
  src/app/timetable/components/CurrentTimeLine/CurrentTimeLine.module.scss
  src/app/timetable/components/CurrentTimeLine/index.tsx
  src/app/timetable/components/Timetable.tsx
  src/app/timetable/components/TypeTimeTable/index.tsx
  src/components/TimeTable/index.tsx
Labels: feat, 5PM

#89 feat: popover 영역 개선
  README.md
  src/app/timetable/TaskSlotContext.ts
  src/app/timetable/TypeContext.ts
  src/app/timetable/components/CurrentTimeLine/index.tsx
  src/app/timetable/components/Timetable.tsx
  src/app/timetable/components/Timetable.type.ts
  src/app/timetable/components/TypeTimeTable/Slot.tsx
  src/app/timetable/components/TypeTimeTable/TaskSlot.tsx
  src/app/timetable/components/TypeTimeTable/TaskSlotItem.tsx
  src/app/timetable/components/TypeTimeTable/TimeSlot.tsx
  src/app/timetable/components/TypeTimeTable/index.tsx
  src/app/timetable/hooks/index.ts
  src/app/timetable/hooks/useClickFloatingInReference.tsx
  src/app/timetable/hooks/useHoverFloatingInReference.tsx
  src/app/timetable/hooks/useRequestAnimationFrame.tsx
  src/app/timetable/page.tsx
  src/app/timetable/utils/index.ts
  src/app/timetable/utils/popover.ts
Labels: 5PM

#93 refactor: db 와 client id 타입 통일
  src/api/hooks/todoHooks.ts
  src/api/hooks/userHooks.ts
  src/api/index.ts
  src/api/queryFn/todoQueryFn.ts
  src/api/queryFn/userQueryFn.ts
  src/app/api/todo/create/route.ts
  src/app/api/todo/delete/route.ts
  src/app/api/todo/getAllByUserId/route.ts
  src/app/api/todo/getOneByTodoId/route.ts
  src/app/api/todo/update/route.ts
  src/app/api/todo/updateTime/route.ts
  src/app/api/user/create/route.ts
  src/app/api/user/delete/route.ts
  src/app/api/user/emailValidation/route.ts
  src/app/api/user/getIdByEmail/route.ts
  src/app/api/user/loginValidation/route.ts
  src/app/apiTest/page.tsx
  src/components/signup/index.tsx
  src/components/todo/TodoComponent.tsx
  src/components/todo/TodoModal.tsx
  src/components/todo/index.tsx
Labels: 5PM, refactor

#97 feat: 헤더 컴포넌트 구현
  custom.d.ts
  src/app/todo/page.tsx
  src/assets/icons/signOut.svg
  src/assets/images/sumtimeRowLogo.png
  src/components/Header/Header.styled.ts
  src/components/Header/index.tsx
  src/components/SignIn/SignOutButton.tsx
  tsconfig.json
Labels: feat, 5PM

#104 feat: useGetAllTodosForTimetable와 timetable 연동 및 todo파트 현재 날짜 수정
  src/api/hooks/todoHooks.ts
  src/app/timetable/components/Timetable.tsx
  src/app/timetable/components/Timetable.type.ts
  src/app/timetable/components/TypeTimeTable/Slot.tsx
  src/app/timetable/components/TypeTimeTable/TaskSlot.tsx
  src/app/timetable/components/TypeTimeTable/TaskSlotItem.tsx
  src/app/timetable/components/TypeTimeTable/index.tsx
  src/app/timetable/mocks/timetableMockData.ts
  src/app/timetable/utils/index.ts
  src/app/timetable/utils/tests/checkOverlapTime.test.ts
  src/components/TimeTable/index.tsx
  src/components/todo/TodoModal.tsx
  src/components/todo/index.tsx
  src/db/schema/todos.ts
Labels: feat, BeforeLunch

#106 feat: 로그인 유효성 검증 적용
  src/components/login/index.tsx
  src/constants/index.ts
  src/lib/auth.ts
Labels: BeforeLunch

#107 feat: taskColor 지정하지 않을 시, random color 적용 & task theme 적용 & provider 묶기
  package-lock.json
  package.json
  src/app/timetable/TypeContext.ts
  src/app/timetable/components/CurrentTimeLine/index.tsx
  src/app/timetable/components/Timetable.tsx
  src/app/timetable/components/Timetable.type.ts
  src/app/timetable/components/TypeTimeTable/Slot.tsx
  src/app/timetable/components/TypeTimeTable/TaskSlot.tsx
  src/app/timetable/components/TypeTimeTable/TaskSlotItem.tsx
  src/app/timetable/components/TypeTimeTable/TimeSlot.tsx
  src/app/timetable/components/TypeTimeTable/index.tsx
  src/app/timetable/contexts/ContextProvider.tsx
  src/app/timetable/contexts/PopoverContext.ts
  src/app/timetable/contexts/TaskSlotContext.ts
  src/app/timetable/contexts/TaskThemeContext.ts
  src/app/timetable/contexts/TypeContext.ts
  src/app/timetable/contexts/index.ts
  src/app/timetable/page.tsx
  src/app/timetable/utils/color.ts
  src/app/timetable/utils/index.ts
Labels: feat, 5PM

#112 feat: slotStyle 추가
  src/app/timetable/components/Timetable.tsx
  src/app/timetable/components/TypeTimeTable/Slot.tsx
  src/app/timetable/components/TypeTimeTable/index.tsx
Labels: feat, 5PM

#113 refactor: popper관련 훅 리펙토링
  src/app/timetable/components/TypeTimeTable/TaskSlotItem.tsx
  src/app/timetable/hooks/index.ts
  src/app/timetable/hooks/useClickFloatingInReference.tsx
  src/app/timetable/hooks/usePopoverFloating.tsx
  src/app/timetable/utils/index.ts
  src/app/timetable/utils/popover.ts
Labels: 5PM, refactor

#120 refactor : Todomal 열리는 두가지 경우를 'mode'를 이용하여 코드 단순화
  src/app/timetable/utils/.color.ts.swp
  src/components/todo/TodoComponent.tsx
  src/components/todo/TodoModal.tsx
  src/components/todo/index.tsx
Labels: refactor

#124 feat: popover content UI 수정
  src/app/timetable/assets/close.png
  src/app/timetable/assets/schedule.png
  src/app/timetable/components/PopoverContent.tsx
  src/app/timetable/components/TaskSlotItem.tsx
  src/app/timetable/components/Timetable.module.scss
  src/app/timetable/hooks/usePopoverFloating.tsx
Labels: feat, BeforeLunch

#122 feat: 회원가입 유효성 검사 기능 구현
  src/components/login/index.tsx
  src/components/signup/Signup.styled.ts
  src/components/signup/index.tsx
  src/constants/index.ts
  src/constants/regExp.ts
  src/themes/index.ts
Labels: feat, BeforeLunch

#125 feat: 이메일, 비밀번호 유효성 검사 로직을 hook으로 분리
  src/components/login/index.tsx
  src/components/signup/index.tsx
  src/hooks/auth/useEmailValidation.ts
  src/hooks/auth/usePasswordValidation.ts
Labels: fix, 5PM

#127 chore: 구글 로그인 기능 삭제
  next.config.mjs
  src/components/login/index.tsx
  src/lib/auth.ts
Labels: chore, 5PM

#129 chore: 메인페이지를 랜딩페이지에서 투두페이지로 변경
  src/app/landing/LandingPage.styled.ts
  src/app/landing/page.tsx
  src/app/page.tsx
  src/app/todo/page.tsx
  src/components/Header/index.tsx
  src/components/login/index.tsx
Labels: chore, 5PM

#131 feat: 로그인한 유저만 메인 페이지 접근 가능하게 설정
  src/lib/auth.ts
  src/middleware.ts
Labels: feat, 5PM

#133 fix : 순환 참조 린트 에러 해결 위한 TodoModalType 파일로 분리
  src/components/todo/TodoModal.tsx
  src/components/todo/index.tsx
  src/types/todo.d.ts
Labels: fix

#132 refactor: 유틸 함수 이름 변경 및 컴포넌트 props명 변경
  src/app/timetable/components/CurrentTimeLine/index.tsx
  src/app/timetable/components/Slot.tsx
  src/app/timetable/components/TaskSlot.tsx
  src/app/timetable/components/TaskSlotItem.tsx
  src/app/timetable/components/TimeSlot.tsx
  src/app/timetable/components/Timetable.type.ts
  src/app/timetable/components/index.tsx
  src/app/timetable/contexts/ContextProvider.tsx
  src/app/timetable/contexts/TaskSlotContext.ts
  src/app/timetable/contexts/TypeContext.ts
  src/app/timetable/page.tsx
  src/app/timetable/utils/css.ts
  src/app/timetable/utils/date/calculation.ts
  src/app/timetable/utils/date/convert.ts
  src/app/timetable/utils/date/filter.ts
  src/app/timetable/utils/index.ts
  src/app/timetable/utils/size.ts
  src/app/timetable/utils/tests/checkOverlapTime.test.ts
  src/app/timetable/utils/timeTable.util.test.ts
  src/components/TimeTable/index.tsx
Labels: BeforeLunch, refactor

#136 feat : session으로 userId를 받아서 todo api호출하도록 수정
  src/components/todo/TodoModal.tsx
  src/components/todo/index.tsx
Labels: feat

#135 feat Todo페이지 디자인 수정 및 달력 레이아웃 추가
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/mainpagetest/page.tsx
  src/components/common/Text.styled.ts
  src/components/todo/Todo.styled.ts
  src/components/todo/TodoComponent.tsx
  src/components/todo/TodoModal.tsx
  src/components/todo/index.tsx
  src/utils/LocalizationProviders.tsx
  src/utils/timeUtils.ts
Labels: feat, design

#141 140-part-name-fit-header-and-contents-in-main-page
  src/app/mainpagetest/page.tsx
  src/app/page.tsx
  src/components/common/BasicContainer.styled.ts
  src/components/todo/TodoModal.tsx
Labels: design, chore

#144 fix: 회원가입 중복체크 안되는 오류 해결
  src/api/hooks/userHooks.ts
  src/api/queryFn/userQueryFn.ts
  src/app/apiTest/page.tsx
  src/components/signup/index.tsx
  src/middleware.ts
Labels: fix

#151 feat: todo table 생성 및 todo api 변경
  migrations/0000_red_jocasta.sql
  migrations/meta/0000_snapshot.json
  migrations/meta/_journal.json
  migrations/relations.ts
  migrations/schema.ts
  src/api/hooks/todoHooks.ts
  src/api/queryFn/todoQueryFn.ts
  src/app/api/todo/create/route.ts
  src/app/apiTest/page.tsx
  src/components/todo/TodoModal.tsx
  src/db/schema.ts
  src/db/schema/categories.ts
  src/db/schema/todos.ts
  src/db/schema/users.ts
Labels: feat, BeforeLunch

#153 feat: timetable컴포넌트 react custom timetable 라이브러리로 변경
  package-lock.json
  package.json
  src/app/timetable/assets/close.png
  src/app/timetable/assets/schedule.png
  src/app/timetable/components/CurrentTimeLine/CurrentTimeLine.module.scss
  src/app/timetable/components/CurrentTimeLine/index.tsx
  src/app/timetable/components/PopoverContent.tsx
  src/app/timetable/components/Slot.tsx
  src/app/timetable/components/TaskSlot.tsx
  src/app/timetable/components/TaskSlotItem.tsx
  src/app/timetable/components/TimeSlot.tsx
  src/app/timetable/components/Timetable.module.scss
  src/app/timetable/components/Timetable.type.ts
  src/app/timetable/components/index.tsx
  src/app/timetable/components/reset.css
  src/app/timetable/constants/index.ts
  src/app/timetable/contexts/ContextProvider.tsx
  src/app/timetable/contexts/PopoverContext.ts
  src/app/timetable/contexts/TaskSlotContext.ts
  src/app/timetable/contexts/TaskThemeContext.ts
  src/app/timetable/contexts/TypeContext.ts
  src/app/timetable/contexts/index.ts
  src/app/timetable/hooks/index.ts
  src/app/timetable/hooks/usePopoverFloating.tsx
  src/app/timetable/hooks/useRequestAnimationFrame.tsx
  src/app/timetable/mocks/timetableMockData.ts
  src/app/timetable/page.tsx
  src/app/timetable/utils/.color.ts.swp
  src/app/timetable/utils/color.ts
  src/app/timetable/utils/css.ts
  src/app/timetable/utils/date/calculation.ts
  src/app/timetable/utils/date/convert.ts
  src/app/timetable/utils/date/filter.ts
  src/app/timetable/utils/index.ts
  src/app/timetable/utils/map.ts
  src/app/timetable/utils/size.ts
  src/app/timetable/utils/tests/checkOverlapTime.test.ts
  src/app/timetable/utils/tests/parseHeightString.test.ts
  src/app/timetable/utils/timeTable.util.test.ts
  src/components/TimeTable/index.tsx
Labels: BeforeLunch

#158 147 feat add category to todo component
  .eslintrc.json
  src/app/day/[year]/[month]/[day]/page.tsx
  src/components/todo/CategoryField.tsx
  src/components/todo/Todo.styled.ts
  src/components/todo/TodoCalendar.tsx
  src/components/todo/TodoModal.tsx
  src/components/todo/TodoPagination.tsx
  src/components/todo/index.tsx
  src/lib/auth.ts
Labels: 5PM

#156 fix: 세미콜론 대신 콜론으로 교체
  src/app/login/loginPage.styled.ts
  src/app/signup/SignupPage.styled.ts
Labels: fix, 5PM

#160 feat: db 재설계
  migrations/0000_loose_surge.sql
  migrations/meta/0000_snapshot.json
  migrations/meta/_journal.json
  migrations/relations.ts
  migrations/schema.ts
  src/api/hooks/todoHooks.ts
  src/api/queryFn/todoQueryFn.ts
  src/app/api/todo/create/route.ts
  src/app/api/todo/delete/route.ts
  src/app/api/todo/getByDate/route.ts
  src/app/api/todo/getOneByTodoId/route.ts
  src/app/api/todo/update/route.ts
  src/app/api/todo/updateTime/route.ts
  src/app/api/user/create/route.ts
  src/app/api/user/delete/route.ts
  src/app/api/user/emailValidation/route.ts
  src/app/api/user/getIdByEmail/route.ts
  src/app/api/user/loginValidation/route.ts
  src/components/todo/TodoList.tsx
  src/components/todo/TodoModal.tsx
  src/db/schema/categories.ts
  src/db/schema/todos.ts
  src/db/schema/users.ts
  src/lib/auth.ts
  src/utils/convertTodosForTimetable.ts
Labels: NOW

#168 feat: mypage 페이지 라우팅 및 layout 구현
  src/app/mypage/MyPage.styled.ts
  src/app/mypage/account/page.tsx
  src/app/mypage/category/page.tsx
  src/app/mypage/faq/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/assets/icons/signOut.svg
  src/components/Header/Header.styled.ts
  src/components/Header/index.tsx
Labels: feat, NOW

#170 feat: category POST API 구현
  src/app/api/category/route.ts
Labels: feat, BeforeLunch

#172 feat: mypage의 account 페이지 구현
  src/app/mypage/account/Account.styled.ts
  src/app/mypage/account/page.tsx
Labels: feat, BeforeLunch

#171 feat: category GET API 구현
  src/app/api/category/[id]/route.ts
  src/app/api/category/route.ts
Labels: feat, BeforeLunch

#169 feat: ColorPicker 컴포넌트 구현
  package-lock.json
  package.json
  src/components/ColorPicker/ColorPicker.styled.ts
  src/components/ColorPicker/index.tsx
  src/components/ColorPickerInput/ColorPickerInput.styled.ts
  src/components/ColorPickerInput/index.tsx
  src/components/common/Flex.styled.ts
  src/components/common/index.ts
  src/components/todo/TodoModal.tsx
Labels: feat, BeforeLunch

#173 feat: Todo Modal 내부에서 Categroy CRUD 작업 가능
  src/app/api/category/route.ts
  src/components/todo/CategoryField.tsx
Labels: feat, design, BeforeLunch

#178 feat: 카테고리 DELETE API 구현
  src/app/api/category/[id]/route.ts
Labels: feat, 5PM

#181 feat: nickname PUT api 생성
  src/app/api/user/[id]/route.ts
Labels: feat, 5PM

#188 feat: 카테고리 구현(api 연동 및 디자인 구현)
  .vscode/settings.json
  src/api/hooks/categoryHooks/useCreateCategory.ts
  src/api/hooks/categoryHooks/useDeleteCategory.ts
  src/api/hooks/categoryHooks/useGetCategory.ts
  src/api/hooks/categoryHooks/useGetCategoryList.ts
  src/api/hooks/categoryHooks/useUpdateCategory.ts
  src/api/queryFn/categoryQueryFn.ts
  src/app/api/user/[id]/route.ts
  src/app/mypage/category/Category.styled.ts
  src/app/mypage/category/CategoryModal.tsx
  src/app/mypage/category/CategoryTableBody.tsx
  src/app/mypage/category/CategoryTableFooter.tsx
  src/app/mypage/category/CategoryTableHeader.tsx
  src/app/mypage/category/page.tsx
  src/components/ColorPicker/index.tsx
  src/components/ColorPickerInput/index.tsx
  src/components/todo/TodoModal.tsx
Labels: feat, 5PM

#195 feat : 리덕스 적용
  .eslintrc.json
  package-lock.json
  package.json
  src/api/hooks/todoHooks.ts
  src/app/StoreProvider.tsx
  src/app/day/[year]/[month]/[day]/page.tsx
  src/app/layout.tsx
  src/components/TimeTable/index.tsx
  src/components/todo/TodoCalendar.tsx
  src/components/todo/TodoComponent.tsx
  src/components/todo/TodoHeader.tsx
  src/components/todo/TodoList.tsx
  src/components/todo/TodoModal.tsx
  src/components/todo/TodoPagination.tsx
  src/components/todo/index.tsx
  src/lib/features/counter/counterSlice.ts
  src/lib/hooks.ts
  src/lib/store.ts
  src/lib/todos/todoDataSlice.ts
  src/lib/todos/todoUISlice.ts
Labels: feat

#189 feat: TodoModal 입력 시 값 검증 로직 추가
  src/components/todo/TodoModal.tsx
Labels: feat, 5PM

#184 feat: color palette 구현
  src/components/ColorPicker/ColorPalette.tsx
  src/components/ColorPicker/ColorPicker.styled.ts
  src/components/ColorPicker/constants.ts
  src/components/ColorPicker/index.tsx
  src/components/ColorPickerInput/index.tsx
  src/utils/index.ts
  src/utils/localStorage.ts
Labels: feat, 5PM

#206 refactor: Restful Todo API 구성 및 에러 수정 등
  src/api/hooks/todoHooks.ts
  src/api/queryFn/categoryQueryFn.ts
  src/api/queryFn/todoQueryFn.ts
  src/api/queryFn/userQueryFn.ts
  src/app/api/category/[id]/route.ts
  src/app/api/category/route.ts
  src/app/api/todo/create/route.ts
  src/app/api/todo/delete/route.ts
  src/app/api/todo/getAllByUserId/route.ts
  src/app/api/todo/getByDate/route.ts
  src/app/api/todo/getOneByTodoId/route.ts
  src/app/api/todo/update/route.ts
  src/app/api/todo/updateTime/route.ts
  src/app/api/todos/[todoId]/route.ts
  src/app/api/todos/route.ts
  src/app/api/user/create/route.ts
  src/app/api/user/delete/route.ts
  src/app/api/user/route.ts
  src/app/mypage/category/CategoryModal.tsx
  src/app/mypage/category/CategoryTableBody.tsx
  src/app/mypage/category/CategoryTableFooter.tsx
  src/components/todo/TodoModal.tsx
  src/db/schema/categories.ts
Labels: fix, BeforeLunch, refactor

#204 feat: 탈퇴 버튼 클릭 시 스낵바 띄우기
  src/app/mypage/account/page.tsx
Labels: feat

#201 feat: 헤더 드롭다운 추가
  src/app/mypage/layout.tsx
  src/components/Header/Header.styled.ts
  src/components/Header/HeaderList.tsx
  src/components/Header/index.tsx
Labels: feat, design, BeforeLunch

#211 fix: api 코드 수정
  src/api/queryFn/categoryQueryFn.ts
Labels: fix, NOW

#209 feat: 타임테이블 text-shadow, color 변경
  package-lock.json
  package.json
  src/components/TimeTable/index.tsx
Labels: feat, 5PM

#212 feat: todo 차트 구현
  package-lock.json
  package.json
  src/components/todo/TodoReport.tsx
  src/components/todo/TodoReport/TodoReport.styled.ts
  src/components/todo/TodoReport/index.tsx
  src/components/todo/TodoReport/util.ts
  src/types/category.d.ts
  src/types/index.ts
  src/types/todo.d.ts
Labels: feat, 5PM

#215 feat: 기록이 없을 때(TodoList가 없을 때) UI 추가
  src/assets/images/emptyTodoIcon.png
  src/components/todo/Todo.styled.ts
  src/components/todo/TodoList.tsx
  src/components/todo/TodoList/EmptyTodoList.tsx
  src/components/todo/TodoList/OpenCreateTodoModalButton.tsx
  src/components/todo/TodoList/TodoList.styled.ts
  src/components/todo/TodoList/index.tsx
  src/components/todo/index.tsx
Labels: feat, 5PM

#220 fix: 과거 시간만 기록 가능하도록 수정
  src/components/todo/TodoModal.tsx
Labels: fix, BeforeLunch

#217 feat: 마이페이지의 카테고리 업데이트 방지 및 생성 시 랜덤 컬러 부여
  src/api/queryFn/categoryQueryFn.ts
  src/app/api/user/route.ts
  src/app/mypage/category/CategoryTableBody.tsx
  src/app/mypage/category/CategoryTableFooter.tsx
  src/app/mypage/category/CategoryTableHeader.tsx
Labels: feat, BeforeLunch

#224 feat: 스크롤 UI 삭제
  src/app/globals.css
Labels: feat, BeforeLunch

#225 design: 에러 문구 색상 및 사이즈 통일
  src/components/signup/Signup.styled.ts
  src/components/signup/index.tsx
Labels: design, BeforeLunch

#219 fix: todo modal에서 todo 삭제 시, 다시 삭제된 todo를 요청하던 버그 해결
  src/components/todo/TodoModal.tsx
Labels: fix, 5PM

#221 fix: 새로고침 시에 현재 날짜로 이동하던 문제 수정
  src/components/todo/TodoHeader.tsx
  src/components/todo/TodoModal.tsx
  src/components/todo/TodoPagination.tsx
  src/lib/todos/todoDataSlice.ts
Labels: fix, 5PM

#228 feat: 삭제 확인 모달 추가
  src/components/todo/TodoModal/DeleteTodoButton.tsx
  src/components/todo/TodoModal/index.tsx
  src/components/todo/TodoModal/modal.styled.ts
Labels: feat, 5PM

#227 feat: enhance ux todo progress status visualization
  src/api/hooks/todoHooks.ts
  src/api/queryFn/todoQueryFn.ts
  src/app/api/todos/[todoId]/route.ts
  src/app/api/todos/route.ts
  src/components/todo/GlowingBorder.tsx
  src/components/todo/Todo.styled.ts
  src/components/todo/Todo.tsx
  src/components/todo/TodoCalendar.tsx
  src/components/todo/TodoComponent.tsx
  src/components/todo/TodoList/TodoWrapper.tsx
  src/components/todo/TodoList/index.tsx
  src/components/todo/TodoModal/index.tsx
  src/components/todo/TodoRecordButton.tsx
  src/components/todo/index.tsx
  src/db/schema/todos.ts
Labels: fix, feat, design, BeforeLunch

#233 feat: 암호화된 password 적용
  package-lock.json
  package.json
  src/app/api/user/route.ts
  src/lib/auth.ts
Labels: feat, 5PM

#235 fix: todoList skeleton 변경 및 todoList가 없을 때 아이콘 이미지 동적으로 변경
  src/api/hooks/todoHooks.ts
  src/components/todo/TodoList/EmptyTodoList.tsx
  src/components/todo/TodoList/index.tsx
  src/components/todo/index.tsx
Labels: feat, 5PM

#238 fix: Record 버튼 중심 틀어짐 수정
  src/components/todo/TodoRecordButton.tsx
Labels: design, 5PM

#252 fix: 미래 시간인 경우, 기록 버튼 비활성화
  src/components/todo/TodoRecordButton.tsx
Labels: fix, 5PM

#245 fix: Todo 시간 수정시 Time Overlap error 예외처리 추가
  src/components/TimeTable/index.tsx
  src/components/todo/TodoModal/index.tsx
  src/components/todo/TodoReport/index.tsx
  src/utils/timetable/convertTodosForTimetable.ts
Labels: fix, BeforeLunch

#249 design: date pagination 7개만 보이도록 수정
  src/components/todo/TodoPagination.tsx
Labels: design, 5PM

#243 fix: 회원가입 에러 해결
  src/components/common/Spinner.tsx
  src/components/signup/index.tsx
  src/constants/regExp.ts
  src/hooks/auth/usePasswordValidation.ts
Labels: fix, BeforeLunch

#258 fix: 버튼 디자인 이슈 수정
  src/components/todo/TodoRecordButton.tsx
Labels: NOW

#257 feat: 404 페이지 생성
  src/app/day/[year]/[month]/[day]/page.tsx
  src/app/mypage/page.tsx
  src/app/not-found.tsx
  src/components/common/LogoCenterLayout.ts
  src/lib/auth.ts
  src/middleware.ts
  src/utils/timeUtils.ts
Labels: feat, 5PM

#240 feat: 차트에 마우스 hover시 보이는 데이터 포맷 변경
  src/components/todo/TodoReport/index.tsx
  src/components/todo/TodoReport/util.ts
Labels: feat, 5PM

#254 feat: title 변경, font 적용, taimeTable defaultvalue를 변경
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.module.css
  src/components/TimeTable/index.tsx
  src/themes/GlobalStyle.tsx
  src/themes/MaterialThemeProvider.tsx
  src/themes/index.ts
Labels: feat, 5PM

#246 feat: 로그인 동작 중 버튼 disable, 로고 이미지 클릭 시, 랜딩 페이지로 이동
  src/components/common/Spinner.tsx
  src/components/common/index.ts
  src/components/login/index.tsx
  src/components/signup/index.tsx
Labels: feat, 5PM

#262 feat: 닉네임 수정 및 닉네임 유효성 검사 추가
  src/app/mypage/account/Account.styled.ts
  src/app/mypage/account/page.tsx
  src/lib/auth.ts
Labels: feat, 5PM

#251 feat: 삭제 확인 모달 공용화 및 카테고리 모달에 적용
  src/app/mypage/category/CategoryModal.tsx
  src/app/mypage/category/CategoryTableBody.tsx
  src/app/mypage/faq/FAQ.styled.ts
  src/app/mypage/faq/page.tsx
  src/app/mypage/layout.tsx
  src/components/Modal/DeleteConfirmModal/index.tsx
  src/components/Modal/modal.styled.ts
  src/components/todo/TodoModal/DeleteTodoButton.tsx
  src/components/todo/TodoModal/index.tsx
Labels: feat, design, 5PM

#239 feat : 투두모달 카테고리 구현(카테고리 url확인)
  src/app/mypage/category/CategoryModal.tsx
  src/components/ColorPickerBox/ColorPickerBox.styled.ts
  src/components/ColorPickerBox/ColorPickerInput.tsx
  src/components/ColorPickerBox/index.tsx
  src/components/ColorPickerBox/useColorPickerFloating.ts
  src/components/ColorPickerInput/ColorPickerInput.styled.ts
  src/components/ColorPickerInput/index.tsx
  src/components/todo/CategoryField.tsx
  src/components/todo/TodoModal/index.tsx
  src/context/TodoDataContext.tsx
  src/context/TodoUIContext.tsx
  src/lib/features/counter/counterSlice.ts
Labels: feat

#259 design: fix header and prevent page scroll
  src/components/Header/Header.styled.ts
  src/components/Header/index.tsx
  src/components/TimeTable/TimeTable.styled.ts
  src/components/common/BasicContainer.styled.ts
  src/components/todo/TodoReport/index.tsx
Labels: design, 5PM

#267 feat: vercel 서버 timezone 설정 코드
  vercel.json
Labels: feat, NOW

#263 refactor: category, todo모달에서 삭제 기능 분리
  src/api/hooks/categoryHooks/useDeleteCategory.ts
  src/app/mypage/category/CategoryModal.tsx
  src/app/mypage/category/DeleteCategoryButton.tsx
  src/components/Modal/DeleteConfirmModal/index.tsx
  src/components/todo/TodoModal/DeleteTodoButton.tsx
  src/components/todo/TodoModal/index.tsx
Labels: feat, BeforeLunch

#268 refactor: todo 생성/수정 시 category color를 가져와 color로 저장
  src/api/hooks/todoHooks.ts
  src/api/queryFn/todoQueryFn.ts
  src/app/api/todos/[todoId]/route.ts
  src/app/api/todos/route.ts
  src/components/todo/TodoModal/index.tsx
Labels: fix, 5PM, refactor

#270 fix: todo 수정 시 시간을 그대로 유지해도 timeOverLap 예외 발생하는 문제 해결
  src/components/todo/TodoModal/index.tsx
Labels: fix, 5PM

#271 refactor: auth style 통합 및 404페이지 라우팅 이슈 해결
  src/app/(auth)/Auth.styled.ts
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/login/loginPage.styled.ts
  src/app/login/page.tsx
  src/app/not-found.tsx
  src/app/signup/SignupPage.styled.ts
  src/app/signup/page.tsx
Labels: fix, 5PM, refactor

#284 fix: timezone 관련 에러 수정
  src/api/hooks/todoHooks.ts
  src/api/queryFn/todoQueryFn.ts
  src/app/api/todos/[todoId]/route.ts
  src/app/api/user/emailValidation/route.ts
  src/app/api/user/getIdByEmail/route.ts
  src/app/api/user/loginValidation/route.ts
  src/app/page.tsx
  src/components/Header/Header.styled.ts
  src/components/Header/index.tsx
  src/components/common/BasicContainer.styled.ts
  src/components/todo/CategoryField.tsx
  src/components/todo/TodoCalendar.tsx
  src/components/todo/TodoList/TodoWrapper.tsx
  src/components/todo/TodoList/index.tsx
  src/components/todo/TodoRecordButton.tsx
  src/components/todo/index.tsx
  src/constants/index.ts
  src/lib/todos/todoDataSlice.ts
Labels: fix, NOW

#287 fix: TodoPage 가로 스크롤 문제 해결
  src/app/layout.tsx
  src/components/common/BasicContainer.styled.ts
Labels: fix, 5PM

#289 fix: 때때로 발생하는 무한 렌더링 에러 해결
  src/components/todo/TodoList/index.tsx
Labels: fix, 5PM

#294 fix: 중복 실행 방지
  src/components/todo/TodoList/TodoWrapper.tsx
  src/components/todo/TodoModal/index.tsx
Labels: fix, 5PM

#295 fix: TimeOverlap 방지 (record 버튼에 검증 로직 추가)
  src/components/todo/TodoList/TodoWrapper.tsx
Labels: fix, 5PM

#296 feat: todo modal category 연결 및 default id 설정, todo modal 역할에 따라 분리,
  src/api/queryFn/categoryQueryFn.ts
  src/app/api/categories/route.ts
  src/app/api/todos/[todoId]/route.ts
  src/components/ColorPickerCircleButton/ColorPickerCircle.styled.ts
  src/components/ColorPickerCircleButton/index.tsx
  src/components/ColorPickerCircleButton/useColorPickerFloating.ts
  src/components/todo/CategoryField.tsx
  src/components/todo/TodoModal/CategoryField.tsx
  src/components/todo/TodoModal/CreateTodoModal.tsx
  src/components/todo/TodoModal/TodoModal.styled.ts
  src/components/todo/TodoModal/UpdateCategoryColorButton.tsx
  src/components/todo/TodoModal/UpdateTodoModal.tsx
  src/components/todo/TodoModal/index.tsx
Labels: feat, BeforeLunch, refactor

#299 fix: ColorPickerBox shift적용해 화면 밖을 벗어나지 않게 번경
  src/components/ColorPickerBox/ColorPickerInput.tsx
  src/components/ColorPickerBox/useColorPickerFloating.ts
Labels: fix, BeforeLunch

#301 design: 마이 페이지 레이아웃 수정
  src/app/mypage/MyPage.styled.ts
  src/app/mypage/layout.tsx
Labels: fix

#304 fix: 기본 카테고리는 수정할 수 없게 변경
  src/components/todo/TodoModal/CategoryField.tsx
Labels: fix

#306 fix: 소수점 길게 표시되는 문제 수정
  README.md
  img.png
Labels: fix, NOW

#308 fix: color modification on category page does not apply to timetable
  src/app/api/categories/[categoryId]/route.ts
  src/app/api/todos/route.ts
Labels: fix, NOW
