Repository Kernel360/FE1_E2E_sumtime, pull requests merged in 2024-07, with the labels that each got.

#8 fix: 프로젝트 폴더 구조 변경
  src/apis/index.ts
  src/assets/index.ts
  src/components/index.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/themes/index.ts
  src/utils/index.ts
Labels: fix

#16 feat: global styles 적용
  src/app/layout.tsx
  src/app/page.tsx
  src/themes/GlobalStyles.tsx
Labels: feat

#25 feat: 로그인 페이지 ui 완성
  src/app/login/loginPage.styled.ts
  src/app/login/page.tsx
  src/components/login/Login.styled.ts
  src/components/login/index.tsx
Labels: feat

#27 fix: global styles 제거 및 globals.css 설정
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/themes/GlobalStyles.tsx
Labels: fix

#20 feat : 공통컴포넌트 구현
  .eslintrc.json
  .prettierrc
  src/components/common/Card.styled.tsx
  src/components/common/Container.styled.tsx
  src/components/common/Flex.styled.tsx
  src/components/common/Input.styled.tsx
  src/components/common/Text.styled.tsx
  src/components/common/index.tsx
Labels: fix, feat
